## valid uuid = 8f4b7b9c-3f7a-4b6c-8b0c-1c9c5b8b9b6a

### 
# @name createDepartment
POST http://localhost:3000/departments
Content-Type: application/json

{
    "name": "Department 1"
}

###

@departmentId = {{createDepartment.response.body.id}}

### 
# @name getDepartments
GET http://localhost:3000/departments
Content-Type: application/json

### 
# @name createEmployee
POST http://localhost:3000/employees
Content-Type: application/json

{
    "first_name": "First name",
    "last_name": "Last name",
    "hire_date": "2011-10-05T14:48:00.000Z",
    "department_id": "{{departmentId}}",
    "phone": "9812383749",
    "address": "Addresssssss 1"
}

###
@employeeId = {{createEmployee.response.body.id}}

### 
# @name listEmployees
GET http://localhost:3000/employees

### 
# @name getEmployee
GET http://localhost:3000/employees/{{employeeId}}

### 
# @name deleteEmployee
DELETE http://localhost:3000/employees/{{employeeId}}
