version: '3'

services:
  app:
    build: .
    command: ./.docker/start.sh
    ports:
      - 3000:3000
    volumes:
      - .:/app
  db:
    image: mysql:8.0.30
    environment:
      - MYSQL_DATABASE=local
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes: 
      - ./.docker/dbdata:/var/lib/mysql